spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: fiap
    password: Q9^3=!mr1&G~
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
